/* Generated from the Material Symbols codepoint table. The font is
   subset to exactly these glyphs, so icons render offline. */
export const ICON: Record<string, string> = {
  'alarm': '\ue855',
  'arrow_back': '\ue5c4',
  'bedtime': '\uf159',
  'book': '\ue86e',
  'bookmark': '\ue8e7',
  'check': '\ue668',
  'check_circle': '\uf0be',
  'checklist': '\ue6b1',
  'chevron_right': '\ue5cc',
  'circle': '\uef4a',
  'close': '\ue5cd',
  'edit_note': '\ue745',
  'filter_list': '\ue152',
  'graphic_eq': '\ue1b8',
  'insights': '\uf092',
  'lock': '\ue899',
  'menu': '\ue5d2',
  'mic': '\ue31d',
  'nights_stay': '\uf174',
  'notifications': '\ue7f5',
  'pause': '\ue034',
  'play_arrow': '\ue037',
  'psychology': '\uea4a',
  'psychology_alt': '\uf8ea',
  'schedule': '\uefd6',
  'share': '\ue80d',
  'stop_circle': '\uef71',
  'timer': '\ue425',
  'visibility': '\ue8f4',
  'waves': '\ue176',
  'expand_more': '\ue5cf',
  'bolt': '\uea0b',
  'self_improvement': '\uea78',
  'keyboard_arrow_up': '\ue316',
  'keyboard_arrow_down': '\ue313',
  'auto_awesome': '\ue65f',
}
export type IconName = keyof typeof ICON
